
export const config = {
  // Credentials
  TWITTER_CONSUMER_KEY: process.env.TWITTER_CONSUMER_KEY,
  TWITTER_CONSUMER_SECRET: process.env.TWITTER_CONSUMER_SECRET,
  TWITTER_ACCESS_TOKEN: process.env.TWITTER_ACCESS_TOKEN,
  TWITTER_ACCESS_TOKEN_SECRET: process.env.TWITTER_ACCESS_TOKEN_SECRET,

  // ID for @VaxHuntersCan (via tweeterid.com)
  VAX_HUNTERS_CAN_ID: '1373531468744552448',
  VAX_HUNTERS_CAN_USERNAME: 'VaxHuntersCan',
  VAX_BOT_ID: '1385030381435506688',

  // Regexes
  POSTAL_CODE_REGEX: /[A-Za-z]\d[A-Za-z]/g,
  UNSUBSCRIBE_REGEX: /unsubscribe/gi,

  // Concurrencies
  NOTIFY_USER_CONCURRENCY: 2,
  SUBSCRIBE_USER_TO_POSTAL_CODES_CONCURRENCY: 2,
  PROCESS_MENTIONS_CONCURRENCY: 2,
  SUBSCRIPTION_CONFIRMATION_CONCURRENCY: 2,

  // Misc
  MENTIONS_FETCH_COUNT: 200,
  MENTIONS_CURSOR_NAME: 'root',
  MENTIONS_POLL_INTERVAL_SECONDS: 30,
}
